# Generated by Django 2.2 on 2019-04-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('preparation_time', models.CharField(max_length=15, verbose_name='Czas przygotowania')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Data dodania')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='Data aktualizacji')),
                ('vegetarian', models.BooleanField(verbose_name='Danie wegetarianskie')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eMenu.Card')),
            ],
        ),
    ]
