# Generated by Django 2.2 on 2019-04-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0002_auto_20190410_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eMenu.Dish'),
        ),
    ]
