# Generated by Django 2.2 on 2019-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0004_auto_20190410_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dish',
            field=models.ManyToManyField(to='eMenu.Dish'),
        ),
    ]
