# Generated by Django 2.2 on 2019-04-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0006_auto_20190410_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('id',)},
        ),
    ]
