# Generated by Django 2.2 on 2019-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0007_auto_20190410_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
    ]
