# Generated by Django 2.2 on 2019-04-10 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0008_auto_20190410_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 17, 1, 44, 564978, tzinfo=utc), verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 17, 1, 44, 565028, tzinfo=utc), verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 17, 1, 44, 535583, tzinfo=utc), verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 17, 1, 44, 535642, tzinfo=utc), verbose_name='Date updated'),
        ),
    ]
