# Generated by Django 2.2 on 2019-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0010_auto_20190410_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date added'),
        ),
    ]
