# Generated by Django 2.2 on 2019-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0011_auto_20190410_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dish',
            field=models.ManyToManyField(blank=True, to='eMenu.Dish'),
        ),
    ]
