# Generated by Django 2.2 on 2019-04-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0012_auto_20190410_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
