# Generated by Django 2.2 on 2019-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0013_dish_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Image'),
        ),
    ]
